const $=s=>document.querySelector(s);
const productsEl=$("#products"),dialog=$("#editor"),form=$("#productForm"),statusEl=$("#status");let products=[];
const api=async(url,opts={})=>{const r=await fetch(url,{headers:{"Content-Type":"application/json"},...opts});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
async function load(){statusEl.textContent="Yükleniyor...";try{products=await api("/api/admin/products");render();statusEl.textContent=`${products.length} ürün`}catch(e){statusEl.textContent="Hata: "+e.message}}
function render(){productsEl.innerHTML=products.map(p=>`<article class="card"><img src="${esc(p.image||'')}" alt=""><h3>${esc(p.name)}</h3><div class="meta"><span>${esc(p.category)}</span><b>${Number(p.price||0).toLocaleString("tr-TR")} TL</b></div><div class="badges">${p.active?'<span class="badge">AKTİF</span>':'<span class="badge">PASİF</span>'}${p.featured?'<span class="badge">ÖNE ÇIKAN</span>':''}</div><div class="buttons"><button onclick="editProduct(${p.id})">Düzenle</button><button class="danger" onclick="deleteProduct(${p.id})">Sil</button></div></article>`).join("")}
window.editProduct=id=>{const p=products.find(x=>x.id===id);if(!p)return;form.reset();for(const k of ["id","slug","name","description","price","sort_order","image","category"]){form.elements[k].value=p[k]??""}form.elements.sizes.value=(p.sizes||[]).join(",");form.elements.colors.value=(p.colors||[]).join(",");form.elements.active.checked=!!p.active;form.elements.featured.checked=!!p.featured;$("#formTitle").textContent="Ürünü Düzenle";dialog.showModal()};
window.deleteProduct=async id=>{if(!confirm("Ürün silinsin mi?"))return;await api("/api/admin/products/"+id,{method:"DELETE"});await load()};
$("#newProduct").onclick=()=>{form.reset();form.elements.active.checked=true;form.elements.sort_order.value=0;$("#formTitle").textContent="Yeni Ürün";dialog.showModal()};$("#reload").onclick=load;
$("#saveBtn").onclick=async()=>{const fd=new FormData(form),obj=Object.fromEntries(fd.entries());obj.price=Number(obj.price||0);obj.sort_order=Number(obj.sort_order||0);obj.sizes=String(obj.sizes||"").split(",").map(x=>x.trim()).filter(Boolean);obj.colors=String(obj.colors||"").split(",").map(x=>x.trim()).filter(Boolean);obj.active=form.elements.active.checked;obj.featured=form.elements.featured.checked;const id=obj.id;delete obj.id;try{if(id)await api("/api/admin/products/"+id,{method:"PUT",body:JSON.stringify(obj)});else await api("/api/admin/products",{method:"POST",body:JSON.stringify(obj)});dialog.close();await load()}catch(e){alert(e.message)}};load();