// Çetin Design production Worker — GitHub is the source of truth.
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const parseProduct=r=>({...r,sizes:JSON.parse(r.sizes||"[]"),colors:JSON.parse(r.colors||"[]"),active:!!r.active,featured:!!r.featured});
const clean=b=>({slug:String(b.slug||"").trim(),name:String(b.name||"").trim(),description:String(b.description||"").trim(),price:Number(b.price||0),image:String(b.image||"").trim(),category:String(b.category||"tshirt").trim(),sizes:JSON.stringify(Array.isArray(b.sizes)?b.sizes:[]),colors:JSON.stringify(Array.isArray(b.colors)?b.colors:[]),active:b.active?1:0,featured:b.featured?1:0,sort_order:Number(b.sort_order||0)});
const imageExt=type=>({"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/avif":"avif","image/gif":"gif"}[type]||"");
export default{async fetch(request,env){const url=new URL(request.url),path=url.pathname;try{
if(path.startsWith("/media/")&&request.method==="GET"){if(!env.MEDIA)return new Response("Media storage not configured",{status:503});const key=decodeURIComponent(path.slice(7));if(!key)return new Response("Not found",{status:404});const object=await env.MEDIA.get(key);if(!object)return new Response("Not found",{status:404});const headers=new Headers();object.writeHttpMetadata(headers);headers.set("etag",object.httpEtag);headers.set("Cache-Control","public, max-age=31536000, immutable");return new Response(object.body,{headers})}
if(path==="/api/products"&&request.method==="GET"){const category=url.searchParams.get("category"),featured=url.searchParams.get("featured");let sql="SELECT * FROM products WHERE active=1",vals=[];if(category){sql+=" AND category=?";vals.push(category)}if(featured==="1")sql+=" AND featured=1";sql+=" ORDER BY sort_order ASC,id ASC";const{results}=await env.DB.prepare(sql).bind(...vals).all();return json(results.map(parseProduct))}
if(path.startsWith("/api/products/")&&request.method==="GET"){const slug=decodeURIComponent(path.split("/").pop());const row=await env.DB.prepare("SELECT * FROM products WHERE slug=? AND active=1").bind(slug).first();return row?json(parseProduct(row)):json({error:"Ürün bulunamadı"},404)}
if(path==="/api/admin/upload"&&request.method==="POST"){if(!env.MEDIA)return json({error:"R2 henüz bağlanmadı. Cloudflare'da MEDIA binding eklenmeli."},503);const form=await request.formData();const file=form.get("file");if(!(file instanceof File)||!file.size)return json({error:"Fotoğraf seçilmedi"},400);const ext=imageExt(file.type);if(!ext)return json({error:"Yalnızca JPG, PNG, WEBP, AVIF veya GIF yüklenebilir"},415);if(file.size>20*1024*1024)return json({error:"Fotoğraf en fazla 20 MB olabilir"},413);const key=`products/${Date.now()}-${crypto.randomUUID()}.${ext}`;await env.MEDIA.put(key,file.stream(),{httpMetadata:{contentType:file.type,cacheControl:"public, max-age=31536000, immutable"},customMetadata:{originalName:file.name}});return json({ok:true,key,url:`/media/${encodeURIComponent(key).replaceAll("%2F","/")}`},201)}
if(path==="/api/admin/products"&&request.method==="GET"){const{results}=await env.DB.prepare("SELECT * FROM products ORDER BY sort_order ASC,id ASC").all();return json(results.map(parseProduct))}
if(path==="/api/admin/products"&&request.method==="POST"){const p=clean(await request.json());if(!p.slug||!p.name)return json({error:"Slug ve ürün adı zorunlu"},400);const q=`INSERT INTO products (slug,name,description,price,image,category,sizes,colors,active,featured,sort_order,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`;const res=await env.DB.prepare(q).bind(p.slug,p.name,p.description,p.price,p.image,p.category,p.sizes,p.colors,p.active,p.featured,p.sort_order).run();return json({ok:true,id:res.meta.last_row_id},201)}
const m=path.match(/^\/api\/admin\/products\/(\d+)$/);if(m&&request.method==="PUT"){const id=Number(m[1]),p=clean(await request.json());const q=`UPDATE products SET slug=?,name=?,description=?,price=?,image=?,category=?,sizes=?,colors=?,active=?,featured=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`;await env.DB.prepare(q).bind(p.slug,p.name,p.description,p.price,p.image,p.category,p.sizes,p.colors,p.active,p.featured,p.sort_order,id).run();return json({ok:true})}if(m&&request.method==="DELETE"){await env.DB.prepare("DELETE FROM products WHERE id=?").bind(Number(m[1])).run();return new Response(null,{status:204})}
return env.ASSETS.fetch(request)}catch(err){return json({error:err.message||"Sunucu hatası"},500)}}};