// Çetin Design production Worker — GitHub is the source of truth.
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const parseProduct=r=>({...r,sizes:JSON.parse(r.sizes||"[]"),colors:JSON.parse(r.colors||"[]"),active:!!r.active,featured:!!r.featured});
const clean=b=>({slug:String(b.slug||"").trim(),name:String(b.name||"").trim(),description:String(b.description||"").trim(),price:Number(b.price||0),image:String(b.image||"").trim(),category:String(b.category||"tshirt").trim(),sizes:JSON.stringify(Array.isArray(b.sizes)?b.sizes:[]),colors:JSON.stringify(Array.isArray(b.colors)?b.colors:[]),active:b.active?1:0,featured:b.featured?1:0,sort_order:Number(b.sort_order||0)});
export default{async fetch(request,env){const url=new URL(request.url),path=url.pathname;try{
if(path==="/api/products"&&request.method==="GET"){const category=url.searchParams.get("category"),featured=url.searchParams.get("featured");let sql="SELECT * FROM products WHERE active=1",vals=[];if(category){sql+=" AND category=?";vals.push(category)}if(featured==="1")sql+=" AND featured=1";sql+=" ORDER BY sort_order ASC,id ASC";const{results}=await env.DB.prepare(sql).bind(...vals).all();return json(results.map(parseProduct))}
if(path.startsWith("/api/products/")&&request.method==="GET"){const slug=decodeURIComponent(path.split("/").pop());const row=await env.DB.prepare("SELECT * FROM products WHERE slug=? AND active=1").bind(slug).first();return row?json(parseProduct(row)):json({error:"Ürün bulunamadı"},404)}
if(path==="/api/admin/products"&&request.method==="GET"){const{results}=await env.DB.prepare("SELECT * FROM products ORDER BY sort_order ASC,id ASC").all();return json(results.map(parseProduct))}
if(path==="/api/admin/products"&&request.method==="POST"){const p=clean(await request.json());if(!p.slug||!p.name)return json({error:"Slug ve ürün adı zorunlu"},400);const q=`INSERT INTO products (slug,name,description,price,image,category,sizes,colors,active,featured,sort_order,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`;const res=await env.DB.prepare(q).bind(p.slug,p.name,p.description,p.price,p.image,p.category,p.sizes,p.colors,p.active,p.featured,p.sort_order).run();return json({ok:true,id:res.meta.last_row_id},201)}
const m=path.match(/^\/api\/admin\/products\/(\d+)$/);if(m&&request.method==="PUT"){const id=Number(m[1]),p=clean(await request.json());const q=`UPDATE products SET slug=?,name=?,description=?,price=?,image=?,category=?,sizes=?,colors=?,active=?,featured=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`;await env.DB.prepare(q).bind(p.slug,p.name,p.description,p.price,p.image,p.category,p.sizes,p.colors,p.active,p.featured,p.sort_order,id).run();return json({ok:true})}if(m&&request.method==="DELETE"){await env.DB.prepare("DELETE FROM products WHERE id=?").bind(Number(m[1])).run();return new Response(null,{status:204})}
return env.ASSETS.fetch(request)}catch(err){return json({error:err.message||"Sunucu hatası"},500)}}};